#!/bin/bash
# Usage: run script in directoru that contains files *.dev.cert and *.dev.p12 if it's sandbox certificates, or files *.prod.cert and *.prod.p12 for production.
# File names for .cer and .p12 should be the same.
#
# (c) Nikita Belosludtcev 22.05.2014
CERT_FILE=""
KEY_FILE=""

for f in *
do
	
	if [[ $f == *.cer ]]
	then
		CERT_FILE="$f"
	fi

	if [[ $f == *.p12 ]]
	then
		KEY_FILE="$f"
	fi
done

if [[ "$CERT_FILE" = "" ]]
then
	echo "Cant find .cer file in current directory"
	exit 1
fi


if [[ "$KEY_FILE" = "" ]]
then
	echo "Cant find .p12 file in current directory"
	exit 1
fi

if [[ "${CERT_FILE%.cer}" != "${KEY_FILE%.p12}" ]]
then
	echo "Cert file and key file names doesn't match"
	exit 1
fi


openssl x509 -in $CERT_FILE -inform der -out "$CERT_FILE.pem"
echo "created $CERT_FILE.pem"
openssl pkcs12 -nocerts -out "$KEY_FILE.pem" -in $KEY_FILE
echo "created $KEY_FILE.pem"
cat "$CERT_FILE.pem" "$KEY_FILE.pem" > "${CERT_FILE%.cer}.pem"
echo "created ${CERT_FILE%.cer}.pem"
if [[ $CERT_FILE = *dev* ]]
then
	 openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert "$CERT_FILE.pem"  -key "$KEY_FILE.pem"
fi
if [[ $CERT_FILE = *prod* ]]
then
	openssl s_client -connect gateway.push.apple.com:2195 -cert "$CERT_FILE.pem"  -key "$KEY_FILE.pem"
fi